### ISSUE TITLE
Which paper?

### ISSUE THREAD

**Issue by HOMGH** [ksenia-konyushkova/LAL-RL#2]
Hi,
Does this repository correspond to any conference/journal paper? I need to have a look into the block diagram or the methodology first.
Thanks.

**Comment by ksenia-konyushkova** [comment]
Hi,

This repository corresponds to the following paper: 
Discovering General-Purpose Active Learning Strategies
Ksenia Konyushkova, Raphael Sznitman, and Pascal Fua
https://arxiv.org/pdf/1810.04114.pdf

Best regards,
Ksenia
